### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by danmichaelo** [skwasjer/cordova-appinfo-plugin#1]
Hi, I also have an appinfo plugin at https://github.com/danmichaelo/cordova-plugin-appinfo . Just came across your plugin, and honestly I kinda like your interface better than mine, so I consider adopting it. Let me know if you'd like to merge with my project, and I'll add you to it.

**Comment by skwasjer** [comment]
Hey hey, sorry for late reply, sounds good to me, grab what you need for the refactor. I have not really looked at it in a few months as I only needed it for one project at the time, some bits need some tweaks and I'm sure some other interesting data could potentially be exposed via the plugin.

Fyi, I can't actively contribute the next 2-3 weeks unfortunately, but will be able to after that.
